development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  database: ai_hrm_dev

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  database: ai_hrm_test
